### ISSUE TITLE
Job/money hud issue with this

### ISSUE THREAD

**Issue by iSentrie** [GMA950/esx_np_skinshop_v2#6]
NEWEST ESX.
Probably same HUD as in picture below, just with money displayed.

I have no idea how it's related, but once I use this script my money/job hud doesn't refresh until I manually do it by dropping or picking money.

This job title don't update also until I change a job.
![image](https://user-images.githubusercontent.com/29688478/78236606-e3b5e100-74e2-11ea-935d-9774e4d29600.png)

Without this resource everything is fine and all details (job, money, black money, bank) loads up in the hud as soon as player spawns. What could cause this, tried troubleshooting for long, no success yet.

**Comment by iSentrie** [comment]
I come up with a simple solution by adding "Citizen.Wait(2000)" in the HUD's playerLoaded event. I still don't understand why this happening, if anyone knows, feel free to tell me. Since this is not a very good solution I made.

**Comment by GroofyTV** [comment]
Could you put the command here maybe or make a screen of it so I know which command should be in which config.
thank you
